services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAX_RETURN_BASE_URL_ARG=https://utbod-skattur.juni.is
        - NATIONAL_REGISTRY_BASE_URL_ARG=https://utbod-thjodskra.juni.is
    environment:
      TAX_RETURN_BASE_URL: https://utbod-skattur.juni.is
      NATIONAL_REGISTRY_BASE_URL: https://utbod-thjodskra.juni.is
    ports:
      - 3000:3000
