services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAX_RETURN_BASE_URL_ARG=http://bidtaxbackendse-eannwhsz-1009143891.eu-west-2.elb.amazonaws.com
    environment:
      TAX_RETURN_BASE_URL: http://bidtaxbackendse-eannwhsz-1009143891.eu-west-2.elb.amazonaws.com
    ports:
      - 3000:3000
